config/routes.rb
Rails.application.routes.draw do

  root 'pages#landing'
  resources :projects

  get 'contact', to: 'pages#contact'



end

app/models/project.rb
class Project < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def landing
  end

  def contact
    
  end

  
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    @projects = Project.all
  end

  def show
    @project = Project.find(params[:id])
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:og="http://ogp.me/ns#"
      xmlns:fb="http://www.facebook.com/2008/fbml">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="Pedro Martin, Junior Web developer, based in London UK" />
  <meta name="Keywords" content="Pedro Martin, Portfolio, Web development, London, javascript, html5, css3, d3.js, General Assembly, ruby on rails">
  <meta property="og:title" content="Pedro Martin | Junior Web Developer">
  <meta property="og:type" content="website">
  <meta property="og:url" content="http://www.pataruco.info">
  <meta property="og:image" content="http://pataruco.s3.amazonaws.com/ga/portfolio/pataruco-info.png">
  <meta property="og:site_name" content="Pedro Martin | Junior Web Developer">
  <meta property="og:description" content="Pedro Martin, Junior Web Developer based in London, UK">
  <meta property="og:locality" content="London">
  <meta property="og:country-name" content="United Kingdom">
  <meta property="og:email" content="pataruco@gmail.com">
  <title>Pedro Martin | Junior Web Developer</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => false %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => false %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header>
    <nav class="navbar navbar-default navigation navbar-fixed-top">
      <div class="container-fluid">
        <ul class="nav nav-tabs">
          <li class='clock-anti' role="presentation"><%= link_to('Home', root_path) %></li>
          <li class='clock-anti' role="presentation"><%=link_to('Projects', projects_path) %></li>
          <!-- <li role="presentation"><%= link_to('Contact', contact_path) %></li> -->
          <li role="presentation">
            <a class='clock' href="https://uk.linkedin.com/in/pataruco" target="_blank">
              <i class="fa fa-lg fa-linkedin-square"></i>
            </a>
          </li>
          <li role="presentation">
            <a class='clock-anti' href="https://github.com/pataruco" target="_blank">
              <i class="fa fa-lg fa-github-square"></i>
            </a>
          </li>
          <li role="presentation">
            <a class='clock' href="https://www.behance.net/pataruco" target="_blank">
              <i class="fa fa-lg fa-behance-square"></i>
            </a>
          </li>
          <li role="presentation">
            <a class='clock-anti' href="mailto:pataruco@gmail.com?subject= We'd like to talk to you about the cucumber joke!" target="_blank">
              <i class="fa fa-lg fa-envelope-square"></i>
            </a>
          </li>
          <li role="presentation">
            <a class='clock' href="http://pataruco.s3.amazonaws.com/CV/CV_Pedro_Martin.pdf" download>
              <i class="fa fa-lg fa-download"></i>
            </a>
          </li>
        </ul>
      </div>
    </nav>
  </header>

<%= yield %>

</body>
</html>

app/views/pages/contact.html.erb
<main>
  <div class="container-fluid">
    <h1>Contact</h1>
    <p>Or more of my stuff...</p>
    <div class="row">
      <div class="col-md-3">
        <h1>
          <a href="https://uk.linkedin.com/in/pataruco" target="_blank">
            <i class="fa fa-4x fa-linkedin-square"></i>
          </a>
        </h1>
      </div>
      <div class="col-md-3">
        <h1>
          <a href="https://github.com/pataruco" target="_blank">
            <i class="fa fa-4x fa-github-square"></i>
          </a>
        </h1>
      </div>
      <div class="col-md-3">
        <h1>
          <a href="https://www.behance.net/pataruco" target="_blank">
            <i class="fa fa-4x fa-behance-square"></i>
          </a>
        </h1>
      </div>
      <div class="col-md-3">
        <h1>
          <a href="mailto:pataruco@gmail.com?subject= We'd like to talk to you about the lettuce joke!" target="_blank">
            <i class="fa fa-4x fa-envelope-square"></i>
          </a>
        </h1>
      </div>
    </div>
  </div>
</main>



  

app/views/pages/landing.html.erb
<main>
  <div class="container-fluid landing" id="who-am-i">
    <h1>Pedro <br>Martin</h1>
    <h2>Web developer junior</h2>
    <p>London</p>
    <p id="arrow" class="caption">scroll down... <span class="glyphicon glyphicon-arrow-down"></span></p>
  </div>
  <div class="container-fluid landing" id="timer">
    <h1>I started coding</h1>
     <p id="timer-counter"><%= Time.local(2015,04,27,9,00,00).ago_in_words %> </p>
     <p id="arrow" class="caption">keep going...<span class="glyphicon glyphicon-arrow-down"></span></p>
  </div>

  <div id="lettuce" class="container-fluid landing">
    <h1>I am fresher than a cucumber</h1>
    <p class="caption">(I know, It was a really bad joke)</p>
    <p>But, I can do some things!</p>
    <p>Check this out!<span class="glyphicon glyphicon-arrow-down"></span></p>
    <p id="arrow" class="caption">(keep scrolling down)</p>
  </div>

  <div class="container-fluid landing" id="code-test">
    <div class="row">
      <div  id="fizzbuzz" class="col-md-6 col-sm-12">
        <h1>Fizz buzz</h1>
        <a class="caption" href="https://en.wikipedia.org/wiki/Fizz_buzz" target="_blank" >What the heck is Fizz buzz?</a>
        <div class="input-group">
          <input type="text" id="FizzBuzz-number" class="form-control" placeholder="Give me a number and I will tell you if it is a Fizz or Buzz" aria-describedby="basic-addon2">
          <span class="input-group-addon" id="fizzButton">Go!</span>
        </div>
        <h2 id="fizzbuzz-result"></h2>
      </div>
      <div id="roman" class="col-md-6 col-sm-12">
        <h1>Roman numeral</h1>
        <a class="caption" href="https://en.wikipedia.org/wiki/Roman_numerals" target="_blank" >What the heck is Roman numeral?</a>
        <div class="input-group">
          <input type="text" id="roman-number" class="form-control" placeholder="Give me a number and I will convert to a Roman Numeral" aria-describedby="basic-addon2">
          <span class="input-group-addon" id="romanButton">Go!</span>
        </div>
        <h2 id="roman-result"></h2>
      </div>
    </div>
  </div>


</main>

app/views/projects/index.html.erb
<main>
  <div class="container-fluid projects">
    <div class="row">
      <% @projects.each do |project| %>
        <div class="col-md-6 col-sm-12">
          <h3 class="project-index-title"><%= link_to(project.name, project_path(project)) %></h3>
          <a href="<%= project_path(project) %>">
            <img src="<%= project.img  %>" class="img-responsive thumbnail">
          </a>
        </div>
      <% end %>
    </div>
  </div>
</main>

app/views/projects/show.html.erb
<main>  
  <div id="show "class="container-fluid project-show">
    <h1 class="project-show-title"> <%= @project.name %> </h1>
    <div class="row">
      <div class="col-md-6">
        <a href="<%= @project.web %>">
          <img src=" <%= @project.img %> " alt="<%= @project.name  %>" class="img-responsive thumbnail">
        </a>
      </div>
      <div class="col-md-6">
        <h3 class="project-show-subtitle">Description:</h3>
        <p class="project-show-p"><%= @project.description %>  </p>
        <h3 class="project-show-subtitle">Technologies:</h3>
        <p class="project-show-p"><%= @project.technologies %>  </p>
        <a href="<%= @project.web %>" class="btn btn-info " role="button" target="_blank">
          <i class="fa fa-4x fa-globe"></i>
        </a>
        <a href=" <%= @project.git %>" class="btn btn-info" role="button" target="_blank">
          <i class="fa fa-4x fa-github-square"></i>
        </a>
      </div>
    </div>
  </div>
</main>
 